import Head from 'next/head'
import styles from "../styles/Home.module.scss"
import Searchbar from '../components/Searchbar/Searchbar'
export default function Home() {
  return (
    <div className={styles.home}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <Searchbar/>
    </div>
  )
}
