import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Searchbar from "../components/Searchbar/Searchbar";
import Slider from "../components/Slider/Slider";
import SongDetails from "../components/SongDetail/SongDetail";
import Details from "../components/HeadingDetails/HeadingDetails";
import { GiFallingStar } from "react-icons/gi";
import {BsArrowRight} from "react-icons/bs"
export default function Home() {
  const songs = [
    {
      songName: "Hello",
      artistName: "Adele",
    },
    {
      songName: "Hello",
      artistName: "Adele",
    },
    {
      songName: "Hello",
      artistName: "Adele",
    },
    {
      songName: "Hello",
      artistName: "Adele",
    },
    {
      songName: "Hello",
      artistName: "Adele",
    },
    {
      songName: "Hello",
      artistName: "Adele",
    },
  ];
  return (
    <div className={styles.home}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Searchbar />
      <Slider
        sliderList={songs}
        slides={SongDetails}
        spaces={20}
        slidePerView={5}
        loop={true}
        navigation={true}
      />
      <Details
        headingName={"Top Collections"}
        Icon={GiFallingStar}
        linkDetails={{ title: "Show More", url: "/album",}}
      />
    </div>
  );
}
